"""
Django settings for DigitalTwinAPI project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import configparser
import os
import sys
from pathlib import Path
import logging
logger = logging.getLogger("DigitalTwinApp")
# from DigitalTwinApp.modules.module_RegHandle import RegHandle

def get_log_base_dir() -> str:
    log_base_dir = ""
    base_path = ""
    if getattr(sys, 'frozen', False):
        base_path = os.path.dirname(sys.executable)
    else:
        base_path = Path(__file__).resolve().parent.parent
    log_base_dir = os.path.join(base_path, 'DT_LOG')

    if not os.path.exists(log_base_dir): 
        os.makedirs(log_base_dir)

    return log_base_dir

def get_Config(filename: str, section: str, option: str, default: str = None) -> str:
    """从指定的配置文件中读取配置参数。

    配置文件一般为ini格式的文件，该函数用于从配置文件中读取指定节内某键的值。

    Arguments:
        filename: 配置文件名。
        section: 节(section)。
        option: 键(key)。
        default: 缺省值，无法读取到指定键值时返回缺省值。
    Returns:
        返回字符串，读取到的键值，即配置信息。
    """
    # # 获取当前文件所在的路径
    # prodir = os.path.split(os.path.realpath(__file__))[0]
    
    # 获取配置文件的完整路径
    if getattr(sys, 'frozen', False):
        base_path = os.path.dirname(sys.executable)
        configpath = os.path.join(base_path, 'DigitalTwinAPI', 'config.ini')
    else:
        base_path = os.path.abspath(os.path.dirname(__file__))
        configpath = os.path.join(base_path, 'config.ini')

    # 创建ConfigParser对象
    conf = configparser.ConfigParser()

    # 读取文件内容，读不到则返回缺省值
    conf.read(configpath)
    config = conf.get(section, option)
    if config:
        return config
    else:
        return default

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# 获取系统安装目录，即根目录
BASE_DIR = Path(__file__).resolve().parent.parent


LOG_DIR = get_log_base_dir()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-f9vtfjqnphh4k%_%##)nce1*8&(02ww^1cp1#0+f$47y*85lfu"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [get_Config("config.ini", "SocketServer", "HOST")]

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "DigitalTwinApp.apps"
]
# TODO(Q)：这两个变量有何用处？
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "DigitalTwinApp.MyCors.My_Cors",
    "DigitalTwinApp.nonreentrant.NonReentrantMiddleware",
    # "DigitalTwinApp.authjump.basic_auth_middleware"
]

ROOT_URLCONF = "DigitalTwinAPI.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "DigitalTwinAPI.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
# 从配置文件config.ini中读取数据库配置信息
DATABASES = {
    "default": {
        "HOST": get_Config("config.ini", "DatabaseServer", "HOST"), 
        "USER": get_Config("config.ini", "DatabaseServer", "USER"), 
        "PASSWORD": get_Config("config.ini", "DatabaseServer", "PASSWORD"), 
        "NAME": get_Config("config.ini", "DatabaseServer", "NAME"), 
        "PORT": get_Config("config.ini", "DatabaseServer", "PORT")
    }
}

# 从配置文件config.ini中读取Socket套接字配置
SOCKET = {
    "HOST": get_Config("config.ini", "SocketServer", "HOST"),
    "PORT": get_Config("config.ini", "SocketServer", "PORT"),
    "MAXLISTEN": get_Config("config.ini", "SocketServer", "MAXLISTEN")
}

# 机器码
# MACHINECODE = {
#     "CODE": RegHandle().get_Machine_Code()  # 获取本地的机器码
# }

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

"""
日志文件的配置，按照下述要求来使用。

"level": "DEBUG"
一般情况下不用，即便是开发过程中也少用，除非是需要输出大量的日志，如循环中使用，此时使用DEBUG级：
logging.debug(...)

"level": "INFO"
开发过程中常用该级别，输出一些对调试有用的信息，该信息对终端用户没有用处，此时使用INFO级：
logging.info(...)

"level": "WARRNING"
软件交付前，需修改为该级别，只输出对售后人员和终端用户有用的信息，此时使用WARRNING级：
logging.warning(...)

一些严重的错误，或捕捉到的例外等，使用ERROR级来记录日志：
logging.error(...)

日志文件的级别可以在配置文件中修改，但记得在交付用户之前修改为WARNING或INFO级别，但
不允许用DEBUG级别。

Examples:
import logging
logger = logging.getLogger("DigitalTwinApp")
logger.info(...)
"""
LOG_LEVEL = get_Config("config.ini", "Log", "LEVEL", "WARNING").upper()
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        }, 
        "simple": {
            "format": "{asctime} {levelname} {filename} {lineno} {funcName} {process:d} {thread:d} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": LOG_LEVEL,
            "class": "logging.FileHandler",
            "filename":  os.path.join(LOG_DIR,"default.log"),
            "formatter": "verbose",
            'encoding': 'utf-8',
        },
        "console_app": {
            "level": LOG_LEVEL,
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file_app": {
            "level": LOG_LEVEL,
            "class": "logging.FileHandler",
            "filename": os.path.join(LOG_DIR,"DigitalTwinApp.log"),
            "formatter": "simple",
            'encoding': 'utf-8',
        },
    },
    "loggers": {
        "DigitalTwinApp": {
            "handlers": ["console_app", "file_app"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django": {
            "handlers": ["file"],
            "level": LOG_LEVEL,
            "propagate": True,
        },
        "apscheduler": {
            "handlers": ["console_app", "file_app"],
            "level": LOG_LEVEL,
            "propagate": False,  # 确保不传播到根记录器
        },
    },
}
